version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - release
    payload:
      maxRunTime: 3600
      image: tarekziade/heavyprofile
      command:  hp-creator /app/profile && hp-archiver /app/profile /app/archives
    metadata:
      name: HeavyProfile
      description: Heavy Profile Generator
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
