version: 0
allowPullRequests: collaborators
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    routes:
      - index.garbage.heavyprofile
    extra:
      github:
        events:
          - push
        branches:
          - master
    payload:
      maxRunTime: 3600
      image: tarekziade/heavyprofile
      command:
          - "/bin/bash"
          - "-c"
          - "git clone https://github.com/tarekziade/heavy-profile"
          - "cd heavy-profile"
          - "pip install --upgrade -r requirements.txt"
          - "python setup.py develop"
          - "hp-creator --max-urls 10 /app/profile"
          - "hp-archiver /app/profile /app/archives"
      artifacts:
        'public':
          type: 'directory'
          path: '/app/archives'
    metadata:
      name: HeavyProfile
      description: Heavy Profile Generator
      owner: tarek@ziade.org
      source: https://github.com/tarekziade/heavy-profile
