version: 0
allowPullRequests: collaborators
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - push
        branches:
          - master
    payload:
      maxRunTime: 3600
      image: tarekziade/heavyprofile
      command:  hp-creator /app/profile && hp-archiver /app/profile /app/archives
      artifacts:
        'public':
          type: 'directory'
          path: '/app/archives'
          expires: '{{#from_now}}7 days{{/from_now}}'
    metadata:
      name: HeavyProfile
      description: Heavy Profile Generator
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
